# SPDX-FileCopyrightText: 2020 tqtezos
# SPDX-License-Identifier: MIT

<<: !include "./hpack/module.yaml"

name:                stablecoin
version:             0.1.0.0

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            FA2-based tezos stablecoin smart contract
category:            Blockchain

description:         Please see the README on GitHub at <https://github.com/tqtezos/stablecoin#readme>

verbatim:
  cabal-version: 2.2

library:
  <<: *lib-common

  dependencies:
    - morley-prelude
    - lorentz
    - morley
    - tasty-quickcheck
    - fmt

tests:
  stablecoin-test:
    <<: *test-common
    source-dirs:
      - test
      - test-common

    dependencies:
      - HUnit
      - morley
      - morley-prelude
      - morley-nettest
      - lorentz
      - tasty
      - tasty-hunit-compat
      - tasty-hspec
      - tasty-quickcheck
      - stablecoin
      - hspec
      - containers

  stablecoin-nettest:
    <<: *test-common
    source-dirs:
      - test-common
      - nettest

    dependencies:
      - containers
      - hspec
      - lorentz
      - morley
      - morley-nettest
      - morley-prelude
      - optparse-applicative
      - stablecoin
